# Generated by Django 5.2.10 on 2026-01-31 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttask',
            name='student',
        ),
    ]
