# Generated by Django 5.2.10 on 2026-02-02 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_studenttask_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttask',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.studentdata'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studenttask',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
